version: '2.3'
services:
  mariadb:
    image: mariadb:lts
    restart: always
    container_name: docker_mariadb
    networks:
      relution-network:
        aliases:
          - mariadb-docker
    environment:
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=relution
      - MYSQL_ROOT_PASSWORD=%MYSQL_ROOT_PASSWORD%
      - MYSQL_USER=relution
      - MYSQL_PASSWORD=%MYSQL_PASSWORD%
    expose:
      - '3306'
    volumes:
      - 'mariadb:/var/lib/mysql'
      - 'C:\Program Files\relution\relution.cnf:/etc/mysql/conf.d/relution.cnf'

  relution:
    image: relution/relution:latest
    restart: always
    container_name: docker_relution
    networks:
      relution-network:
        aliases:
          - relution-docker
    depends_on:
      - mariadb
    links:
      - mariadb
    environment:
      - TZ=Europe/Berlin
      - DATABASE_TYPE=mysql
      - DATABASE_URL=jdbc:mariadb://mariadb-docker/relution?useServerPrepStmts=true
      - DATABASE_USER=relution
      - DATABASE_PWD=%MYSQL_PASSWORD%
      - SMTP_HOST=%SMTP_HOSTNAME%      
      - RELUTION_SERVER_EXTERNALURL=%EXT_HOSTNAME_URL%
      - RELUTION_SYSTEM_ADMIN_PASSWORD=%SYSTEM_ADMIN_PASSWORD%
      - RELUTION_SYSTEM_ADMIN_EMAIL=%SYSTEM_ADMIN_EMAIL%
    expose:
      - '8080'
      - '8099'

  nginx:
    image: nginx:stable
    restart: always
    container_name: docker_nginx
    networks:
      relution-network:
        aliases:
          - nginx-docker
    depends_on:
      - relution
    links:
      - relution
    environment:
     - TZ=Europe/Berlin
     - NGINX_HOST=%EXT_HOSTNAME%
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - 'C:\Program Files\relution\relution-nginx.conf:/etc/nginx/conf.d/relution-nginx.conf'
     - 'C:\Program Files\relution\server.pem:/etc/nginx/server.pem'
     - 'C:\Program Files\relution\server.key:/etc/nginx/server.key'

volumes:
  mariadb:

networks:
  relution-network:
    external:
      name: nat
